return {
  -- require("plugins.themes.cobalt2"),
  -- require("plugins.themes.doom-one"),
  -- require("plugins.themes.everforest-nvim"),
  -- require("plugins.themes.github-nvim-theme"),
  require("plugins.themes.gruvbox-baby"),
  -- require("plugins.themes.gruvbox-material"),
  -- require("plugins.themes.kanagawa"),
  -- require("plugins.themes.material"),
  -- require("plugins.themes.material-nvim"),
  -- require("plugins.themes.neosolarized"),
  -- require("plugins.themes.nord-nvim"),
  -- require("plugins.themes.nvim-base16"), -- Lots of themes with all major names
  -- require("plugins.themes.nvim-quietlight"),
  -- require("plugins.themes.onedark-nvim"),
  -- require("plugins.themes.papercolor-theme"), -- For better readability of the code in different languages.
  -- require("plugins.themes.readable-nvim"),    -- For better readability of the code in different languages.
  -- require("plugins.themes.rose-pine"),
  require("plugins.themes.solarized-osaka-nvim"),
  -- require("plugins.themes.zenbones"),



  -- Configure LazyLite to load gruvbox
  {
    "aamir-sultan/LazyLite",
    opts = {
      -- colorscheme = "blue",
      -- colorscheme = "cobalt2",
      -- colorscheme = "doom-one",
      -- colorscheme = "duckbones",
      -- colorscheme = "forestbones",
      -- colorscheme = "github_dark",
      -- colorscheme = "github_dark_colorblind",
      -- colorscheme = "github_dark_default",
      -- colorscheme = "github_dark_dimmed",
      -- colorscheme = "github_dark_high_contrast",
      -- colorscheme = "github_dark_tritanopia",
      -- colorscheme = "github_light",
      -- colorscheme = "github_light_default",
      -- colorscheme = "github_light_high_contrast",
      -- colorscheme = "github_light_tritanopia",
      -- colorscheme = "gruvbox-baby",
      -- colorscheme = "kanagawa",
      -- colorscheme = "kanagawabones",
      -- colorscheme = "kanagawa-dragon",
      -- colorscheme = "kanagawa-lotus",
      -- colorscheme = "kanagawa-wave",
      -- colorscheme = "material-darker",
      -- colorscheme = "neobones",
      -- colorscheme = "NeoSolarized",
      -- colorscheme = "noctu",
      -- colorscheme = "nord",
      -- colorscheme = "nordbones",
      -- colorscheme = "nvim-quietlight",
      -- colorscheme = "onedark",
      -- colorscheme = "PaperColor",
      -- colorscheme = "randombones",
      -- colorscheme = "rosebones",
      -- colorscheme = "seoulbones",
      -- colorscheme = "solarized",
      colorscheme = "solarized-osaka",
      -- colorscheme = "tokyobones",
      -- colorscheme = "tokyonight-moon",
      -- colorscheme = "vimbones",
      -- colorscheme = "zenbones",
      -- colorscheme = "zenburned",
      -- colorscheme = "zenwritten",
    },
  },
}
